version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: schejulo_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: schejulo
      POSTGRES_PASSWORD: schejulo
      POSTGRES_DB: schejulo
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U schejulo -d schejulo']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: schejulo_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@schejulo.local
      PGADMIN_DEFAULT_PASSWORD: schejulo
    ports:
      - '5050:80'
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
